name: ExtDN Unit Tests
on: [push, pull_request]

env:
  MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
  MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
  MODULE_NAME: ${{ secrets.MODULE_NAME }}
  COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
  PHPUNIT_FILE: "phpunit.xml.dist"

jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-unit-tests/8.1@master
        env:
          MAGENTO_VERSION: "2.4.5-p1"
