name: ExtDN Unit Tests
on: [push, pull_request]

env:
  MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
  MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
  MODULE_NAME: ${{ secrets.MODULE_NAME }}
  COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}

jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extdn/github-actions-m2/magento-unit-tests/7.3@master
        env:
          MAGENTO_VERSION: '2.3.7-p4'
      - uses: extdn/github-actions-m2/magento-unit-tests/7.4@master
        env:
          MAGENTO_VERSION: '2.4.3-p3'
      - uses: extdn/github-actions-m2/magento-unit-tests/8.1@master
        env:
          MAGENTO_VERSION: '2.4.4-p3'
      - uses: extdn/github-actions-m2/magento-unit-tests/8.1@master
        env:
          MAGENTO_VERSION: "2.4.5-p2"
      - uses: extdn/github-actions-m2/magento-unit-tests/8.1@master
        env:
          MAGENTO_VERSION: "2.4.6"
