name: Code Style
on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run
